### ISSUE TITLE
undefined is not an object (evaluating 'navigator.permissions.query')

### ISSUE THREAD

**Issue by SergeTandoku** [orna-memory-hunting/project#13]
@https://orna-memory-hunting.github.io/page/amitie-new.js:193:24
safeExecute@https://orna-memory-hunting.github.io/lib/utils.js:46:16
module code@https://orna-memory-hunting.github.io/page/amitie-new.js:6:12
evaluate@[native code]
moduleEvaluation@[native code]

@https://orna-memory-hunting.github.io/page/amitie-new.js:783:38
safeExecute@https://orna-memory-hunting.github.io/lib/utils.js:46:16
updateGithubLink@https://orna-memory-hunting.github.io/page/amitie-new.js:773:16
toggleAmitieInfo@https://orna-memory-hunting.github.io/page/amitie-new.js:213:23
answerClick@https://orna-memory-hunting.github.io/page/amitie-new.js:93:23

**Comment by IgorNovozhilov** [comment]
fixed [4a992c2374f8d48cb71acc5b25a119499c627f56](https://github.com/orna-memory-hunting/orna-memory-hunting.github.io/commit/4a992c2374f8d48cb71acc5b25a119499c627f56)
